name: "Argoclima Dummy Server"
description: "Argoclima Dummy Server as HA Add-On"
version: "1.1.1"
slug: "argoclima_dummy"
init: false
arch:
  - aarch64
  - amd64
url: "https://github.com/nyffchanium/argoclima-integration"
ingress: true
ports:
  8080/tcp: 8183
ports_description:
  8080/tcp: Dummy Server for Argoclima Ulisse AC
